// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1573030909);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1573031029);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1573031149);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1573030789);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1573030669);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.search.countryCode", "ES");
user_pref("browser.search.region", "ES");
user_pref("datareporting.sessions.current.activeTicks", 0);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 1510);
user_pref("datareporting.sessions.current.main", 122);
user_pref("datareporting.sessions.current.startTime", "1568703411083");
user_pref("datareporting.sessions.current.totalTime", 5442);
user_pref("datareporting.sessions.currentIndex", 2);
user_pref("datareporting.sessions.previous.0", "{\"s\":1568368232842,\"a\":1,\"t\":118,\"c\":true,\"m\":102,\"fp\":1996,\"sr\":-1}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1568368878183,\"a\":0,\"t\":189,\"c\":true,\"m\":112,\"fp\":1626,\"sr\":-1}");
user_pref("extensions.blocklist.lastModified", "Fri, 01 Nov 2019 13:00:20 GMT");
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.e10s.rollout.hasAddon", false);
user_pref("extensions.e10sBlockedByAddons", true);
user_pref("extensions.getAddons.cache.lastUpdate", 1573030909);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20191007090452");
user_pref("extensions.lastAppVersion", "60.9.0");
user_pref("extensions.lastPlatformVersion", "60.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"wetransfer@extensions.thunderbird.net\":\"ae3285ee-f0b8-4c49-9624-a57c02d694b2\"}");
user_pref("idle.lastDailyNotification", 1573033220);
user_pref("mail.ab_remote_content.migrated", 1);
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.default_charsets.migrated", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.ui-rdf.version", 17);
user_pref("mailnews.database.global.datastore.id", "7d0e969a-53c8-43d9-b657-170ee7807e4");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page_override.mstone", "60.9.0");
user_pref("mailnews.tags.$label1.color", "#FF0000");
user_pref("mailnews.tags.$label1.tag", "Importante");
user_pref("mailnews.tags.$label2.color", "#FF9900");
user_pref("mailnews.tags.$label2.tag", "Trabajo");
user_pref("mailnews.tags.$label3.color", "#009900");
user_pref("mailnews.tags.$label3.tag", "Personal");
user_pref("mailnews.tags.$label4.color", "#3333FF");
user_pref("mailnews.tags.$label4.tag", "Por hacer");
user_pref("mailnews.tags.$label5.color", "#993399");
user_pref("mailnews.tags.$label5.tag", "Más tarde");
user_pref("mailnews.tags.version", 2);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("places.database.lastMaintenance", 1573033220);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("services.blocklist.addons.checked", 1573030984);
user_pref("services.blocklist.clock_skew_seconds", 45);
user_pref("services.blocklist.gfx.checked", 1573030984);
user_pref("services.blocklist.last_etag", "\"1572998416349\"");
user_pref("services.blocklist.last_update_seconds", 1573030984);
user_pref("services.blocklist.onecrl.checked", 1573030984);
user_pref("services.blocklist.pinning.checked", 1573030984);
user_pref("services.blocklist.plugins.checked", 1573030984);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1573033220);
user_pref("toolkit.telemetry.cachedClientID", "191e77ad-15b7-4254-acd3-dcf1fc3db684");
user_pref("toolkit.telemetry.previousBuildID", "20191007090452");
user_pref("toolkit.telemetry.prompted", 2);
